class Question {
  final int id;
  final String storyline;
  final String question;
  final List<String> options;
  final int correctAnswer; // Index of correct answer (0-based)
  final String category;
  final String phase;

  Question({
    required this.id,
    required this.storyline,
    required this.question,
    required this.options,
    required this.correctAnswer,
    required this.category,
    required this.phase,
  });
}

class QuestionBank {
  static final List<Question> allQuestions = [
    // Pre-Visit Journey 1 (Q1-Q3)
    Question(
      id: 1,
      category: 'Pre-Visit (Journey 1)',
      phase: 'Preparation',
      storyline: 'You\'re scheduled to meet Mr. Ade, the owner of "Ade\'s Lounge," a high-potential outlet in Lagos. Heineken has recently launched a new trade marketing activation in the area, and Ade\'s Lounge is a key target for execution excellence.',
      question: 'Before heading out, what\'s the most effective way to prepare?',
      options: [
        'Go straight to the outlet without preparation',
        'Review Ade\'s Lounge\'s past sales data on SEM/QuickDrinks and previous visit notes',
        'Skip trade marketing checks',
        'Wait until the meeting to set objectives',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 2,
      category: 'Pre-Visit (Journey 1)',
      phase: 'Preparation',
      storyline: 'You discover that Ade\'s Lounge has not yet subscribed to the latest "Heineken Champions League Viewing Night" activation.',
      question: 'What should you do before the visit?',
      options: [
        'Ignore the activation gap',
        'Prepare tailored sales arguments linking the activation to increased footfall',
        'Assume Mr. Ade already knows about it',
        'Focus only on pricing',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 3,
      category: 'Pre-Visit (Journey 1)',
      phase: 'Preparation',
      storyline: 'You\'re packing for the visit.',
      question: 'Which preparation ensures excellent execution?',
      options: [
        'Bring only a price list',
        'Carry necessary POS materials, and ensure your device is fully charged',
        'Rely on verbal persuasion alone',
        'Skip materials since execution can wait',
      ],
      correctAnswer: 1,
    ),
    
    // During-Visit Phase 1: Engage (Q4-Q5)
    Question(
      id: 4,
      category: 'During-Visit (Journey 1)',
      phase: 'Engage the Customer',
      storyline: 'You arrive at Ade\'s Lounge. Mr. Ade is busy but welcomes you. You need to build rapport before diving into business.',
      question: 'What\'s the best way to engage him?',
      options: [
        'Jump straight into product features',
        'Ask about his general welfare and recent customer turnout',
        'Ignore his personal style',
        'Move directly to closing the sale',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 5,
      category: 'During-Visit (Journey 1)',
      phase: 'Engage the Customer',
      storyline: 'Mr. Ade mentions his lounge recently hosted a local music night.',
      question: 'How do you adapt your style?',
      options: [
        'Show interest in how the event went and link Heineken\'s activations to entertainment',
        'Ignore his comment and push discounts',
        'Keep the conversation strictly transactional',
        'Avoid linking to his motivations',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 2: Understand Needs (Q6-Q7)
    Question(
      id: 6,
      category: 'During-Visit (Journey 1)',
      phase: 'Understand Customer Needs',
      storyline: 'Mr. Ade mentions that his customers love Heineken but often ask for promotions or events that make the brand feel more exciting.',
      question: 'How do you uncover his deeper needs?',
      options: [
        'Use questioning and listening techniques to confirm what drives his customers',
        'Assume promotions are unnecessary',
        'Focus only on pricing',
        'Avoid discussing customer motivations',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 7,
      category: 'During-Visit (Journey 1)',
      phase: 'Understand Customer Needs',
      storyline: 'While carrying out outlet execution check on SEM, you notice unavailability of key focus brands.',
      question: 'What should you do?',
      options: [
        'Document gaps and prioritize them for discussion',
        'Ignore the gaps',
        'Assume customers don\'t notice',
        'Focus only on promotions',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 3: Sell Benefits (Q8-Q9)
    Question(
      id: 8,
      category: 'During-Visit (Journey 1)',
      phase: 'Sell the Benefits',
      storyline: 'You now tailor your sales presentation to Mr. Ade highlighting the execution gaps and the proposed Heineken activation. Mr. Ade agrees to restock the unavailable brands but showed concerns about competition running activation on mainstream brands in nearby outlets.',
      question: 'Which approach best sells the benefits?',
      options: [
        'Emphasize Heineken\'s global brand strength and propose a unique activation that differentiates Ade\'s Lounge from competitors',
        'Focus only on listing product features without linking them to customer drivers',
        'Offer discounts as the main solution, ignoring long-term brand positioning',
        'Avoid addressing competition and stick to generic sales arguments',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 9,
      category: 'During-Visit (Journey 1)',
      phase: 'Sell the Benefits',
      storyline: 'Mr. Ade worries about attracting younger customers.',
      question: 'How do you respond?',
      options: [
        'Highlight Heineken\'s strong appeal to youth through music and sports activations',
        'Focus only on price cuts',
        'Avoid tailoring solutions',
        'Push generic features',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 4: Close Sale (Q10-Q11)
    Question(
      id: 10,
      category: 'During-Visit (Journey 1)',
      phase: 'Close the Sale',
      storyline: 'Mr. Ade nods and shows interest. He asks, "So what\'s the next step?"',
      question: 'What should you do?',
      options: [
        'Identify the buying signals and gain agreement on the quantity of Heineken to buy',
        'Keep repeating features',
        'Avoid negotiation principles',
        'Leave without confirming execution',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 11,
      category: 'During-Visit (Journey 1)',
      phase: 'Close the Sale',
      storyline: 'Mr. Ade hesitates about the quantity of Heineken to purchase for the activation.',
      question: 'How do you handle this?',
      options: [
        'Acknowledge Mr. Ade\'s concern, but explain the expected increase in footfall from the activation and the positive impact on ROI',
        'Ignore his concern',
        'Push harder without listening',
        'Drop the proposal entirely',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 5: Execute (Q12-Q13)
    Question(
      id: 12,
      category: 'During-Visit (Journey 1)',
      phase: 'Execute',
      storyline: 'Agreement is reached: Ade\'s Lounge will run a Heineken weekend activation. Now it\'s about execution excellence.',
      question: 'What\'s the most critical action here?',
      options: [
        'Guide Mr. Ade to place an order for the agreed quantity of Heineken on QuickDrinks',
        'Leave execution for the next visit',
        'Ignore consumer drivers',
        'Focus only on closing sales',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 13,
      category: 'During-Visit (Journey 1)',
      phase: 'Execute',
      storyline: 'To maximize sell-out during the activation.',
      question: 'What should you leverage?',
      options: [
        'Deploy activation posters in the impact zone and ensure adequate forward stock is available in the cooling assets',
        'Ignore consumer trends',
        'Focus only on stock levels',
        'Rely on discounts alone',
      ],
      correctAnswer: 0,
    ),
    
    // Post-Visit (Q14-Q15)
    Question(
      id: 14,
      category: 'Post-Visit (Journey 1)',
      phase: 'Post-Visit',
      storyline: 'You leave Ade\'s Lounge having achieved your set objectives for the call. The real impact now depends on follow-through.',
      question: 'What\'s the most important step after the visit?',
      options: [
        'Register the agreements in SEM and follow up with the fulfilment agent to ensure order delivery',
        'Wait until the next visit to record notes',
        'Skip reflection',
        'Avoid market intelligence',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 15,
      category: 'Post-Visit (Journey 1)',
      phase: 'Post-Visit',
      storyline: 'After reviewing the visit, you realize Mr. Ade responded well to tailored activations but less to pricing discussions.',
      question: 'What should you do?',
      options: [
        'Identify areas to improve your style and approach, and note down observations to guide your next visit',
        'Ignore the insight',
        'Keep repeating the same approach',
        'Avoid recording lessons learned',
      ],
      correctAnswer: 0,
    ),
    
    // Pre-Visit Journey 2 (Q16-Q23)
    Question(
      id: 16,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'You\'re scheduled to visit Chima\'s Bar, a medium-sized but strategically located outlet in Abuja. A new trade activation has just begun in the region.',
      question: 'Before leaving for Chima\'s Bar, what is the MOST important data to review?',
      options: [
        'Competitors\' TV campaigns only',
        'Last visit notes, ordering patterns, and stock trends on SEM/QuickDrinks',
        'Only the POS items available in the warehouse',
        'Discount history only',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 17,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'You observe a recent downward trend in Chima\'s volume.',
      question: 'What should you prepare before the visit?',
      options: [
        'Ignore the trend',
        'Prepare diagnostic questions to understand the potential root cause',
        'Prepare only a discount negotiation strategy',
        'Carry no materials',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 18,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'A new "Heineken Music Encore Nights" activation is relevant in the territory.',
      question: 'What should you do?',
      options: [
        'Assume Chima already knows about it',
        'Identify how this activation aligns with his customer base',
        'Focus only on pricing',
        'Skip activations during this visit',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 19,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'Your SEM notes show Chima rarely adopts visual merchandising recommendations.',
      question: 'How do you prepare?',
      options: [
        'Bring additional, compelling visibility arguments',
        'Bring no POS materials',
        'Avoid discussing merchandising',
        'Focus only on stock pressure',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 20,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'You notice that last visit objectives were partially achieved.',
      question: 'What now?',
      options: [
        'Ignore the incomplete actions',
        'Update this visit\'s objectives based on pending tasks',
        'Start completely new objectives',
        'Avoid reviewing old objectives',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 21,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'Before leaving, your phone\'s battery is low.',
      question: 'What is the best action?',
      options: [
        'Go without a charger',
        'Fully charge your device and carry backup power',
        'Assume you won\'t need SEM on the field',
        'Cancel the visit',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 22,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'The outlet has recently expanded its seating capacity.',
      question: 'What should you prepare for?',
      options: [
        'Only a product list',
        'Proposals that leverage increased consumer traffic potential',
        'No change in preparation',
        'Focus solely on competitor pricing',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 23,
      category: 'Pre-Visit (Journey 2)',
      phase: 'Preparation',
      storyline: 'A new product has been launched.',
      question: 'What should you do?',
      options: [
        'Prepare launch education materials and compelling selling arguments',
        'Wait to discuss it in future visits',
        'Focus only on existing brands',
        'Avoid mentioning the new product',
      ],
      correctAnswer: 0,
    ),
    
    // During-Visit Journey 2 - Phase 1: Engage (Q24-Q27)
    Question(
      id: 24,
      category: 'During-Visit (Journey 2)',
      phase: 'Engage the Customer',
      storyline: 'You arrive at Chima\'s Bar. He looks stressed but welcomes you.',
      question: 'The best way to start the conversation is to:',
      options: [
        'Jump into stock issues immediately',
        'Warmly ask about how he\'s doing and his business performance',
        'Ask only about competitor presence',
        'Go straight into closing',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 25,
      category: 'During-Visit (Journey 2)',
      phase: 'Engage the Customer',
      storyline: 'Chima tells you he just renovated the outdoor seating area.',
      question: 'What should you do?',
      options: [
        'Ignore it',
        'Compliment the change and link it to activation opportunities',
        'Focus only on discounts',
        'Change the topic',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 26,
      category: 'During-Visit (Journey 2)',
      phase: 'Engage the Customer',
      storyline: 'He appears in a hurry.',
      question: 'How do you adapt?',
      options: [
        'Continue at normal pace',
        'Keep communication short, focused and respectful of his time',
        'Leave without trying',
        'Request a long meeting',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 27,
      category: 'During-Visit (Journey 2)',
      phase: 'Engage the Customer',
      storyline: 'His staff interrupts with a question.',
      question: 'What do you do?',
      options: [
        'Get irritated',
        'Allow the interruption and maintain rapport',
        'Ask them to leave rudely',
        'Stop the visit abruptly',
      ],
      correctAnswer: 1,
    ),
    
    // Phase 2: Understand Needs (Q28-Q35)
    Question(
      id: 28,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'Chima complains about slow weekend traffic.',
      question: 'What is the best way to understand the issue?',
      options: [
        'Make assumptions',
        'Ask probing questions on customer motivations',
        'Focus only on pricing',
        'Avoid discussing needs',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 29,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'You notice empty spaces in the cooler meant for premium brands.',
      question: 'What now?',
      options: [
        'Ignore it',
        'Document the gap and explore reasons for low replenishment',
        'Blame staff immediately',
        'Switch topic',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 30,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'Chima says consumers prefer experiential events.',
      question: 'What should you do?',
      options: [
        'Avoid discussing activations',
        'Explore which events drive the most traffic',
        'Assume all activations work equally',
        'Push only promotions',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 31,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'Chima mentions a competitor offered a "football night kit".',
      question: 'The best engagement response is:',
      options: [
        'Ignore the comment',
        'Acknowledge it and ask what customers liked about it',
        'Say competitors\' activities don\'t matter',
        'Change the subject',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 32,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'During the outlet execution check, you see outdated POS items.',
      question: 'What is the right action?',
      options: [
        'Ignore them',
        'Highlight as an opportunity for refreshed visibility',
        'Remove them without permission',
        'Discuss only stock levels',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 33,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'Chima says he\'s unsure about space for new placements.',
      question: 'You should:',
      options: [
        'Force the placement',
        'Explore flexible options and co-create solutions',
        'Drop visibility completely',
        'Stop the conversation',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 34,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'A staff member mentions customers asking for colder beer.',
      question: 'What should you do?',
      options: [
        'Ignore staff input',
        'Ask follow-up questions on cooling asset usage',
        'Tell staff it\'s irrelevant',
        'Change topic',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 35,
      category: 'During-Visit (Journey 2)',
      phase: 'Understand Customer Needs',
      storyline: 'PICOS reveals a competitor\'s activation booth at the entrance.',
      question: 'Your move?',
      options: [
        'Pretend not to see it',
        'Document and explore its impact with Chima',
        'Criticize the competitor',
        'Drop needs discussion',
      ],
      correctAnswer: 1,
    ),
    
    // Phase 3: Sell Benefits (Q36-Q43)
    Question(
      id: 36,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'You propose a weekend mini activation to drive footfall.',
      question: 'What\'s the best selling approach?',
      options: [
        'Highlight only product features',
        'Link benefits directly to weekend traffic challenges',
        'Focus solely on discounts',
        'Avoid activation conversation',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 37,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'Chima fears he may not manage the activation crowd.',
      question: 'What do you do?',
      options: [
        'Ignore concern',
        'Provide simple activation support solutions',
        'Pressure him',
        'Drop proposal',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 38,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'He questions ROI.',
      question: 'Your best response?',
      options: [
        'Provide evidence and expected uplift',
        'Avoid discussing ROI',
        'Promise unrealistic returns',
        'Change subject',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 39,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'Chima says he wants to attract young professionals.',
      question: 'Best selling argument?',
      options: [
        'Focus only on price',
        'Link Heineken\'s premium positioning to aspirational consumers',
        'Avoid segmentation',
        'Push random SKUs',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 40,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'He doubts his staff can execute.',
      question: 'You should:',
      options: [
        'Offer simple execution guidelines',
        'Ignore',
        'Suggest they "figure it out"',
        'Drop execution planning',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 41,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'You notice he responds well to visuals.',
      question: 'What should you do?',
      options: [
        'Use POS mockups/samples to strengthen the pitch',
        'Keep arguments verbal',
        'Avoid visuals',
        'Show irrelevant materials',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 42,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'You sense he prefers visual explanations.',
      question: 'How do you respond?',
      options: [
        'Keep everything verbal',
        'Use your tablet/POS visuals to illustrate',
        'Avoid showing materials',
        'Show irrelevant slides',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 43,
      category: 'During-Visit (Journey 2)',
      phase: 'Sell the Benefits',
      storyline: 'He is unsure about consumer engagement tools.',
      question: 'Best move?',
      options: [
        'Demonstrate simple engagement tools linked to Heineken activations',
        'Avoid discussion',
        'Focus only on stock',
        'Present only complex tools',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 4: Close Sale (Q44-Q50)
    Question(
      id: 44,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'Chima seems persuaded but hesitant.',
      question: 'What is the best next step?',
      options: [
        'Identify buying signals and align on activation quantities',
        'Keep repeating benefits',
        'End the meeting abruptly',
        'Discuss unrelated topics',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 45,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He asks for your final recommendation.',
      question: 'What should you do?',
      options: [
        'Offer an accurate and expected forward stock required for activation',
        'Be vague',
        'Avoid recommending',
        'Focus only on complaints',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 46,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He hesitates on stock size.',
      question: 'What now?',
      options: [
        'Acknowledge and explain expected uplift based on activation',
        'Ignore hesitation',
        'Pressure him for large orders',
        'Drop stock discussion',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 47,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He asks about competition activities in nearby bars.',
      question: 'What do you do?',
      options: [
        'Explain how Heineken differentiates his outlet with premium activations',
        'Panic',
        'Avoid the question',
        'Focus only on price',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 48,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He wants reassurance on after sales support.',
      question: 'You should:',
      options: [
        'Clarify support steps and timelines',
        'Avoid the topic',
        'Promise unrealistic support',
        'Change subject',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 49,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He asks you to summarize the agreement.',
      question: 'You should:',
      options: [
        'Summarize key points clearly',
        'Be vague',
        'Start a new topic',
        'Avoid summarizing',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 50,
      category: 'During-Visit (Journey 2)',
      phase: 'Close the Sale',
      storyline: 'He wants clarity on activation materials.',
      question: 'What now?',
      options: [
        'Confirm materials, availability, and timelines',
        'Skip details',
        'Promise without checking',
        'Avoid discussing materials',
      ],
      correctAnswer: 0,
    ),
    
    // Phase 5: Execute (Q51-Q55)
    Question(
      id: 51,
      category: 'During-Visit (Journey 2)',
      phase: 'Execute',
      storyline: 'Agreement achieved; time to execute.',
      question: 'What is the most important action?',
      options: [
        'Ensure order is placed on QuickDrinks',
        'Leave execution for another day',
        'Focus only on talking',
        'Ignore execution',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 52,
      category: 'During-Visit (Journey 2)',
      phase: 'Execute',
      storyline: 'You observed non-compliance with the planogram in the chiller product arrangement.',
      question: 'What should you do?',
      options: [
        'Guide staff to correct product arrangement in the chiller',
        'Ignore it',
        'Blame the outlet',
        'Remove products without consent',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 53,
      category: 'During-Visit (Journey 2)',
      phase: 'Execute',
      storyline: 'Activation posters must be placed.',
      question: 'What is your move?',
      options: [
        'Place them strategically in the impact zones',
        'Keep them in your bag',
        'Give all to Chima to figure out',
        'Avoid POS usage',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 54,
      category: 'During-Visit (Journey 2)',
      phase: 'Execute',
      storyline: 'Stock looks insufficient for the activation.',
      question: 'What now?',
      options: [
        'Assist with forward stock planning and order placement on QuickDrinks',
        'Ignore',
        'Tell them it\'s fine',
        'Cancel activation',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 55,
      category: 'During-Visit (Journey 2)',
      phase: 'Execute',
      storyline: 'Staff seem confused about activation flow.',
      question: 'What do you do?',
      options: [
        'Explain step by step execution',
        'Avoid supporting',
        'Only give materials',
        'Leave immediately',
      ],
      correctAnswer: 0,
    ),
    
    // Post-Visit Journey 2 (Q56-Q60)
    Question(
      id: 56,
      category: 'Post-Visit (Journey 2)',
      phase: 'Post-Visit',
      storyline: 'You have left Chima\'s Bar.',
      question: 'What should you do first?',
      options: [
        'Register agreements and actions in SEM',
        'Wait till next week',
        'Avoid documentation',
        'Do nothing',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 57,
      category: 'Post-Visit (Journey 2)',
      phase: 'Post-Visit',
      storyline: 'Before leaving.',
      question: 'What is critical?',
      options: [
        'Evaluate the visit jointly',
        'Leave without feedback',
        'Avoid discussion',
        'Skip reflection',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 58,
      category: 'Post-Visit (Journey 2)',
      phase: 'Post-Visit',
      storyline: 'You observed strong competitor activity.',
      question: 'What is best?',
      options: [
        'Record market intelligence',
        'Ignore it',
        'Drop insights',
        'Pretend it didn\'t happen',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 59,
      category: 'Post-Visit (Journey 2)',
      phase: 'Post-Visit',
      storyline: 'You realize Chima responds well to activation-based value selling.',
      question: 'What should you do?',
      options: [
        'Capture this insight to refine your future approach',
        'Ignore',
        'Repeat previous style without changes',
        'Avoid learning from visits',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 60,
      category: 'Post-Visit (Journey 2)',
      phase: 'Post-Visit',
      storyline: 'Future improvement planning.',
      question: 'How do you improve future visits?',
      options: [
        'Use feedback and data to refine strategies',
        'Ignore feedback',
        'Repeat same approach',
        'Avoid change',
      ],
      correctAnswer: 0,
    ),
    
    // QuickDrinks & SEM Questions (Q61-Q80)
    Question(
      id: 61,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A retailer calls you frustrated because they cannot log into QuickDrinks and cannot remember their password. They urgently need to place an order to avoid going out of stock.',
      question: 'What should you do to help them resolve this quickly and professionally to avoid sales loss?',
      options: [
        'Call the support team on 08006000000',
        'Tell the customer there is nothing you can do',
        'Log in for the customer using your own phone',
        'Escalate the issue',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 62,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A customer reaches out asking why their order has been showing a blue label on the QuickDrinks app for hours. They are worried that there might be a delay.',
      question: 'What does this blue status indicate so you can reassure them correctly?',
      options: [
        'On the way',
        'Sent to Distributor',
        'Cancelled by Me',
        'Denied',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 63,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A new customer wants to place their first order and asks you to show them the correct steps.',
      question: 'Which one of these steps is NOT part of ordering on QuickDrinks?',
      options: [
        'Click \'Place order\' on the home screen to start ordering',
        'Select your distributor (delivery charge and hours visible), proceed',
        'Use brand filter to find products',
        'Add quantity per product and place order',
        'Log out, clear cache, and log in again',
      ],
      correctAnswer: 4,
    ),
    Question(
      id: 64,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A customer wants to quickly find products that fit their preferred budget and category.',
      question: 'Which of the following is NOT a sorting/filtering option available on QuickDrinks?',
      options: [
        'Brand',
        'Price',
        'Distributor',
        'Product Category',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 65,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A retailer asks about completing an order.',
      question: 'After adding items to your cart, what is the very last thing you must do to complete the order on QuickDrinks?',
      options: [
        'Select preferred delivery date',
        'Click \'Send order\' and receive confirmation',
        'Add products to cart and place order',
        'A and B',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 66,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'You are a territory sales executive, and you want to unlock growth in your territory.',
      question: 'What actions would you prioritize to unlock sustainable growth? (Select 2)',
      options: [
        'Improve outlet coverage by prioritizing high-potential outlets and off Trade',
        'Launch a new premium SKU immediately',
        'Offer a short-term trade promotion to boost immediate volume',
        'Fix in-outlet execution (availability, visibility, planogram, facing)',
      ],
      correctAnswer: 0, // Note: This is a multi-select question, showing first correct answer
    ),
    Question(
      id: 67,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A customer contacts you in panic because their order suddenly turned red on QuickDrinks. They think the order failed.',
      question: 'What does the red status mean?',
      options: [
        'On the way',
        'Sent to Distributor',
        'Cancelled by Me/Distributor',
        'Denied',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 68,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'A retailer wants to save time during login and asks what happens if they tick the "Remember Me" box on the QuickDrinks login screen.',
      question: 'What does this feature do?',
      options: [
        'Backend will always remember customers',
        'Customers are special to the organisation',
        'Customers can log in next time without typing Username and Password',
        'The app will save their last order',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 69,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'You are reviewing notifications with a retailer, and they ask what it means when a message appears with a blue background on QuickDrinks.',
      question: 'What does this indicate?',
      options: [
        'Message has been read',
        'Not been read',
        'Cancelled',
        'Delivered',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 70,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'Emeka Bar placed an online order on Thursday. The warehouse fulfilled the order and successfully delivered it to him on Friday, which was also the expected delivery date.',
      question: 'Based on the loyalty program rules, on which day should Emeka expect the points to appear in his wallet?',
      options: [
        'Friday',
        'Saturday',
        'Monday',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 71,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'Amaka Bar, a new B2B customer, has just been onboarded on the Quick Drinks app. Shortly after completing the process, she asks you how many loyalty points she should expect to receive as her welcome bonus.',
      question: 'What is the correct response?',
      options: [
        '0 point',
        '50 points',
        '100 points',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 72,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'Chidi has been actively ordering on the Quick Drinks app and has accumulated enough loyalty points to redeem an item.',
      question: 'Where can he redeem his item on the Quick Drinks application?',
      options: [
        'Loyalty Shop',
        'Quick Drinks Shop',
        'MyJara Shop',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 73,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'During your Steering the Frontline Meeting, your new SR noticed the different customer personas displayed on SEM.',
      question: 'Which one is not a customer persona on SEM?',
      options: [
        'Chinedu Flex',
        'Iya Dele',
        'Chukwuebuka',
        'Mama Faith',
        'Iya Bola',
      ],
      correctAnswer: 4,
    ),
    Question(
      id: 74,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'During a coaching session with your field team, one of the new SRs comes across the acronym TPM.',
      question: 'What is the full meaning of TPM?',
      options: [
        'Trade Promotion Management',
        'Trade Production Manager',
        'Trade Promotion Manager',
        'Trade Productivity Management',
      ],
      correctAnswer: 0,
    ),
    Question(
      id: 75,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'During a store visit, your SR is reviewing execution metrics and repeatedly sees the acronym OEC on the dashboard.',
      question: 'What is the full meaning of OEC?',
      options: [
        'Outlet Execution Chart',
        'Outlet Execution Check',
        'Outlet Exercise Check',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 76,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'While on the field, your SR reports that a survey is not displaying in an outlet on the SEM app.',
      question: 'Which of the following is NOT an appropriate option to resolve this issue?',
      options: [
        'Sync SEM app',
        'Escalate via GSD for resolution',
        'Ignore and continue work',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 77,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'During field operations, one of your SRs encounters a system issue on the SEM app. You advise him to check if the Company Portal is updated/signed in and then synchronize again.',
      question: 'When does this solution apply?',
      options: [
        'Cannot capture GPS',
        'I don\'t have a Visit Plan',
        'My last synced date is not changing',
        'SEM has stopped',
      ],
      correctAnswer: 3,
    ),
    Question(
      id: 78,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'Your SR notices that an asset previously recorded in one outlet has now been physically moved to another location.',
      question: 'What is the correct term for the process of moving assets from one outlet to another on Asset Manager?',
      options: [
        'Asset Movement',
        'Asset Deployment',
        'Asset Redeployment',
        'Asset Outlet Change',
      ],
      correctAnswer: 2,
    ),
    Question(
      id: 79,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'You\'ve just been deployed to a new territory and asked to map all distributors according to their classification.',
      question: 'Which of the following is NOT a Distributor classification on Smart Sales?',
      options: [
        'Wholesales Independent',
        'Sub Distributor',
        'Mega Distributor',
        'Key Distributor',
      ],
      correctAnswer: 1,
    ),
    Question(
      id: 80,
      category: 'QuickDrinks & SEM',
      phase: 'Technical Knowledge',
      storyline: 'You are analyzing the types of Assets currently being deployed through the Asset Manager platform.',
      question: 'Which of the following Assets is NOT currently deployed through Asset Manager?',
      options: [
        'Signages',
        'Fridges',
        'Television',
        'Freezers',
      ],
      correctAnswer: 2,
    ),
  ];
}
